# Generated by Django 5.1.7 on 2025-04-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_tasks',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='users_tasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
