# Generated by Django 5.1.7 on 2025-04-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_task_id_users_tasks_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks_task_categories',
            old_name='category_option_id',
            new_name='category_option',
        ),
        migrations.RenameField(
            model_name='tasks_task_categories',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='tasks_task_categories',
            old_name='task_category_id',
            new_name='task_category',
        ),
    ]
