# Generated by Django 5.1.7 on 2025-04-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_category_option_id_tasks_task_categories_category_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_option',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tasks.task_category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='media/task/task.png', null=True, upload_to='tasks/<built-in function id>/'),
        ),
        migrations.AlterField(
            model_name='tasks_task_categories',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.task'),
        ),
    ]
