# Generated by Django 5.1.7 on 2025-04-16 08:26

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_category_option_task_category_alter_task_image_and_more'),
        ('workspaces', '0002_alter_users_workspaces_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_option',
            name='task_category',
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='defaults/task/task.png', null=True, upload_to=tasks.models.user_image_upload_path),
        ),
        migrations.CreateModel(
            name='workspace_category_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category_option')),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tasks.task_category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_category_option',
            },
        ),
    ]
