# Generated by Django 5.1.7 on 2025-04-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_workspace'),
        ('workspaces', '0003_alter_users_workspaces_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_option',
            name='task_categories',
            field=models.ManyToManyField(related_name='category_cptions', through='tasks.workspace_category_option', to='tasks.task_category'),
        ),
        migrations.AddField(
            model_name='task_category',
            name='workspaces',
            field=models.ManyToManyField(related_name='task_categories', through='tasks.workspace_category_option', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace_category_option',
            name='category_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tasks.category_option'),
        ),
        migrations.AlterField(
            model_name='workspace_category_option',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task_category'),
        ),
        migrations.AlterUniqueTogether(
            name='workspace_category_option',
            unique_together={('workspace', 'task_category'), ('workspace', 'task_category', 'category_option')},
        ),
        migrations.AlterModelTable(
            name='workspace_category_option',
            table=None,
        ),
    ]
