# Generated by Django 5.1.7 on 2025-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(default='2026-04-12'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default='2025-04-12'),
        ),
    ]
