# Generated by Django 5.1.7 on 2025-04-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_end_date_alter_task_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspace_category_option',
            table='workspace_category_option',
        ),
    ]
