# Generated by Django 5.1.7 on 2025-04-21 23:13

from django.db import migrations , models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_workspace_category_option_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspace_category_option',
            unique_together={('workspace', 'task_category', 'category_option')},
        ),
        migrations.AlterField(
            model_name='category_option',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category_option',
            name='task_categories',
            field=models.ManyToManyField(related_name='category_options', through='tasks.workspace_category_option', to='tasks.task_category'),
        ),
        migrations.AlterField(
            model_name='category_option',
            name='tasks',
            field=models.ManyToManyField(related_name='category_options', through='tasks.tasks_task_categories', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task_category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
