# Generated by Django 5.1.7 on 2025-04-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_workspace_category_option_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspace_category_option',
            unique_together=set(),
        ),
    ]
