
############# Tasks  ###################

GET http://127.0.0.1:8000/api/tasks/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTc2NTc5LCJpYXQiOjE3NDQ1NzI5NzksImp0aSI6IjVkMmViMmIyYzg5ODRiMGU5ZTc2NThhNzA0MGIyNDE1IiwidXNlcl9pZCI6MX0.9huCqHQ_BfvqatYIVeNRNi-BZttWG799BioXVSIN88Q

###

POST http://127.0.0.1:8000/api/tasks/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTc2NTc5LCJpYXQiOjE3NDQ1NzI5NzksImp0aSI6IjVkMmViMmIyYzg5ODRiMGU5ZTc2NThhNzA0MGIyNDE1IiwidXNlcl9pZCI6MX0.9huCqHQ_BfvqatYIVeNRNi-BZttWG799BioXVSIN88Q
Content-Type: application/json

{
    "title": "Task 1",
    "description": "description for task 1",
    "start_date": "2025-04-12",
    "workspace": 1,
    "owner": 1,   
    "items": [
        {
            "task_category": 2,
            "category_option": 1
        }
    ]

}

###

clGET http://127.0.0.1:8000/api/tasks/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTc2NTc5LCJpYXQiOjE3NDQ1NzI5NzksImp0aSI6IjVkMmViMmIyYzg5ODRiMGU5ZTc2NThhNzA0MGIyNDE1IiwidXNlcl9pZCI6MX0.9huCqHQ_BfvqatYIVeNRNi-BZttWG799BioXVSIN88Q

###

PATCH  http://127.0.0.1:8000/api/tasks/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTc2NTc5LCJpYXQiOjE3NDQ1NzI5NzksImp0aSI6IjVkMmViMmIyYzg5ODRiMGU5ZTc2NThhNzA0MGIyNDE1IiwidXNlcl9pZCI6MX0.9huCqHQ_BfvqatYIVeNRNi-BZttWG799BioXVSIN88Q
Content-Type: application/json

{
    "title": "Task 1 Edited"
}

###

PUT  http://127.0.0.1:8000/api/tasks/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTc2NTc5LCJpYXQiOjE3NDQ1NzI5NzksImp0aSI6IjVkMmViMmIyYzg5ODRiMGU5ZTc2NThhNzA0MGIyNDE1IiwidXNlcl9pZCI6MX0.9huCqHQ_BfvqatYIVeNRNi-BZttWG799BioXVSIN88Q
Content-Type: application/json

{
    "title": "Task 1 Edited",
    "description": "description for task 1 Edited",
    "start_date": "2025-04-12",
    "owner": 1,
    "items": [
        {
            "task_category": 2,
            "category_option": 1
        }
    ]
}

###

DELETE http://127.0.0.1:8000/api/tasks/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTc2NTc5LCJpYXQiOjE3NDQ1NzI5NzksImp0aSI6IjVkMmViMmIyYzg5ODRiMGU5ZTc2NThhNzA0MGIyNDE1IiwidXNlcl9pZCI6MX0.9huCqHQ_BfvqatYIVeNRNi-BZttWG799BioXVSIN88Q

##TODO




############# Category_Options ###################

GET http://127.0.0.1:8000/api/category_options/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAwNDI1LCJpYXQiOjE3NDQ4OTY4MjUsImp0aSI6IjA3Nzg0M2Y4M2FmNjQwMzE4ZGY3NWRhMTU3YWNhNDg1IiwidXNlcl9pZCI6MX0.XEWUIgmul0rRIoAPcW1pPzx94ddzArAJB5fc5Ikwac8

###

POST http://127.0.0.1:8000/api/category_options/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAwNDI1LCJpYXQiOjE3NDQ4OTY4MjUsImp0aSI6IjA3Nzg0M2Y4M2FmNjQwMzE4ZGY3NWRhMTU3YWNhNDg1IiwidXNlcl9pZCI6MX0.XEWUIgmul0rRIoAPcW1pPzx94ddzArAJB5fc5Ikwac8
Content-Type: application/json

{
    "name": "Hoo",
}


###

PUT http://127.0.0.1:8000/api/category_options/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODgzOTU2LCJpYXQiOjE3NDQ4ODAzNTYsImp0aSI6Ijg4Yzc1NzdiZTg5ZjQ1ZDY4YjZhYzNiMzFiY2ExODE2IiwidXNlcl9pZCI6MX0.ERDA3k6R0tDBC_gmzQ_JxQtkLcB-6fVg1EOlgb_hLus
Content-Type: application/json

{
    "name": "easy1",
    "options":[
        {
            "workspace": 1,
            "task_category":2
        }
    ]
}


###


GET http://127.0.0.1:8000/api/category_options/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTYwOTIzLCJpYXQiOjE3NDQ1NTczMjMsImp0aSI6ImVhZGMyYzg3NDkxODQ3OTBiMTllYTllNjRjZDM2NGI0IiwidXNlcl9pZCI6MX0.57yedo7lD3Ad_10pBcicuVgJSfOuIZhqCwrXIobgRtw


###

DELETE http://127.0.0.1:8000/api/category_options/3/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTYwOTIzLCJpYXQiOjE3NDQ1NTczMjMsImp0aSI6ImVhZGMyYzg3NDkxODQ3OTBiMTllYTllNjRjZDM2NGI0IiwidXNlcl9pZCI6MX0.57yedo7lD3Ad_10pBcicuVgJSfOuIZhqCwrXIobgRtw




############# Task_Categories ###################



GET http://127.0.0.1:8000/api/task_categories/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAwNDI1LCJpYXQiOjE3NDQ4OTY4MjUsImp0aSI6IjA3Nzg0M2Y4M2FmNjQwMzE4ZGY3NWRhMTU3YWNhNDg1IiwidXNlcl9pZCI6MX0.XEWUIgmul0rRIoAPcW1pPzx94ddzArAJB5fc5Ikwac8



###


POST http://127.0.0.1:8000/api/task_categories/ HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAwNDI1LCJpYXQiOjE3NDQ4OTY4MjUsImp0aSI6IjA3Nzg0M2Y4M2FmNjQwMzE4ZGY3NWRhMTU3YWNhNDg1IiwidXNlcl9pZCI6MX0.XEWUIgmul0rRIoAPcW1pPzx94ddzArAJB5fc5Ikwac8
Content-Type: application/json

{
    "name": "Category 4",

}

###

GET http://127.0.0.1:8000/api/task_categories/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAwNDI1LCJpYXQiOjE3NDQ4OTY4MjUsImp0aSI6IjA3Nzg0M2Y4M2FmNjQwMzE4ZGY3NWRhMTU3YWNhNDg1IiwidXNlcl9pZCI6MX0.XEWUIgmul0rRIoAPcW1pPzx94ddzArAJB5fc5Ikwac8

###

PUT http://127.0.0.1:8000/api/task_categories/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTYwOTIzLCJpYXQiOjE3NDQ1NTczMjMsImp0aSI6ImVhZGMyYzg3NDkxODQ3OTBiMTllYTllNjRjZDM2NGI0IiwidXNlcl9pZCI6MX0.57yedo7lD3Ad_10pBcicuVgJSfOuIZhqCwrXIobgRtw
Content-Type: application/json

{
    "name": "Category 1 e"
}


###

DELETE http://127.0.0.1:8000/api/task_categories/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTYwOTIzLCJpYXQiOjE3NDQ1NTczMjMsImp0aSI6ImVhZGMyYzg3NDkxODQ3OTBiMTllYTllNjRjZDM2NGI0IiwidXNlcl9pZCI6MX0.57yedo7lD3Ad_10pBcicuVgJSfOuIZhqCwrXIobgRtw

###

POST http://127.0.0.1:8000/api/task_categories/assign/ HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAwNDI1LCJpYXQiOjE3NDQ4OTY4MjUsImp0aSI6IjA3Nzg0M2Y4M2FmNjQwMzE4ZGY3NWRhMTU3YWNhNDg1IiwidXNlcl9pZCI6MX0.XEWUIgmul0rRIoAPcW1pPzx94ddzArAJB5fc5Ikwac8
Content-Type: application/json

{
    "task_category": 4,
    "options": [
        {
            "id": 1,
            "name": "easy1"
        },
        {
            "id": 5,
            "name": "Hoo"
        }
    ]
}