
GET http://127.0.0.1:8000/api/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NTM3NzAwLCJpYXQiOjE3NDQ1MzQxMDAsImp0aSI6ImYwZDRlNzM2MmU0OTRjNjQ5NTYzZWE4MDdkYzJiNGRmIiwidXNlcl9pZCI6Mn0.-EX5dTyqN-cBZlHa20onHZHlzkCgr8g9F_IudM75SxI

###
GET http://127.0.0.1:8000/api/users/1/ HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mjg3MjAzLCJpYXQiOjE3NDQyODM2MDMsImp0aSI6IjMxODE4MWE0MTcyZDQ1MWI4YjI3NWMzMThlOTRmYzY4IiwidXNlcl9pZCI6MX0.tKN0jl09rA0bD_9LvoeuxH1u_Ozd4GpWuX7LFNC4Xqc
CLIENT-USERNAME: Majd
CLIENT-SECRET: sl:a,"hd?1he:l3z4dxvx=f2342jr0io9)54(-)[4j2f+(d0j545323fs\*sdf/sks%dnv,`ls#dfkl}


###
POST http://127.0.0.1:8000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "fullname": "Ali",
    "email": "alialmusfi@gmail.com",
    "password": "12345678"
}

###
POST http://127.0.0.1:8000/api/users/token/ HTTP/1.1
Content-Type: application/json

{

    "email": "alialmusfi@gmail.com",
    "password": "12345678"

}

###
POST http://127.0.0.1:8000/api/users/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NDM3MDEzMCwiaWF0IjoxNzQ0MjgzNzMwLCJqdGkiOiIzMjVkOWM1M2QxNjE0MGJmODZkZTU2NDA0MGE3ZDM1MCIsInVzZXJfaWQiOjF9.QWXrjaT7bRVFSK855vQC-rhAyfn-lm4g2xPRFWrKJuA"
}

###
PATCH http://127.0.0.1:8000/api/users/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzAxMTc4LCJpYXQiOjE3NDQyOTc1NzgsImp0aSI6ImM4ZDczMmNlODJlMzRjZmU4ZTdmMGViN2VjNTI5OTdiIiwidXNlcl9pZCI6Mn0.PDLMEbkl6nnQ-nsDt5lTkO2KeOLIn3LohAanSBtQ-Wk

{
    "fullname": "john-doe"
}

###
PATCH http://127.0.0.1:8000/api/users/change_password/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzAzMTkyLCJpYXQiOjE3NDQyOTk1OTIsImp0aSI6ImE1NDc5NDVmNzIzNTQwNmQ4NzZkZTE0YjdmMGY3YjZmIiwidXNlcl9pZCI6Mn0.gk0qswFey7kvPg68-zKboywIGxabzPaCZAXWDaydXi4

{
    "old_password": "testtest2",
    "new_password": "testtest"
}

###
PATCH http://127.0.0.1:8000/api/users/change_image/ HTTP/1.1
Content-Type: multipart/form-data;  boundary=MyBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mzk1NTY5LCJpYXQiOjE3NDQzOTE5NjksImp0aSI6IjA1YjAxMDQxNDM3MzQ1NThhMDc0ZDQyNjhjNzRlNGZkIiwidXNlcl9pZCI6Mn0.QdJyvuzVGgTShf8GgAYFAYpmjSvsZD21IvjLZ0R-pGY

# must send from postman
--MyBoundary
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpeg

image=< ../../temp_assets/example.jpg
--MyBoundary
