GET http://127.0.0.1:8000/api/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mjg3MTY4LCJpYXQiOjE3NDQyODM1NjgsImp0aSI6IjBmYjBiYWM0MjNhNzQ0MGQ5YWZlMGUwZGIyYzc1ODAwIiwidXNlcl9pZCI6Mn0.XfLEuet8vdXB1xdY7QrrndC0N38Gc0uEB9MkJk2c94Y

###
GET http://127.0.0.1:8000/api/users/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mjg3MjAzLCJpYXQiOjE3NDQyODM2MDMsImp0aSI6IjMxODE4MWE0MTcyZDQ1MWI4YjI3NWMzMThlOTRmYzY4IiwidXNlcl9pZCI6MX0.tKN0jl09rA0bD_9LvoeuxH1u_Ozd4GpWuX7LFNC4Xqc

###
POST http://127.0.0.1:8000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "fullname": "",
    "email": "",
    "password": ""
}

###
POST http://127.0.0.1:8000/api/users/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "j@j.com",
    "password": "testtest"
}

###
POST http://127.0.0.1:8000/api/users/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NDM3MDEzMCwiaWF0IjoxNzQ0MjgzNzMwLCJqdGkiOiIzMjVkOWM1M2QxNjE0MGJmODZkZTU2NDA0MGE3ZDM1MCIsInVzZXJfaWQiOjF9.QWXrjaT7bRVFSK855vQC-rhAyfn-lm4g2xPRFWrKJuA"
}

###
PUT http://127.0.0.1:8000/api/users/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mjk3NTAyLCJpYXQiOjE3NDQyOTM5MDIsImp0aSI6ImRlY2RkYzRmM2U4YTRmYzg5N2M5ZDc4NTcyM2JhYjU2IiwidXNlcl9pZCI6Mn0.rHOwOBTs2fvdRv9QN8SoJNY71qN1BwzwdRCJaQ5nIAA

{
    "fullname": "john-doe"
}

###
