# Generated by Django 5.1.7 on 2025-04-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_workspaces',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='users_workspaces',
            old_name='workspace_id',
            new_name='workspace',
        ),
    ]
