# Generated by Django 5.1.7 on 2025-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_workspaces',
            name='user_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('partner', 'Partner'), ('can_edit', 'Can Edit'), ('can_view', 'Can View')], default='can_view', max_length=8),
        ),
    ]
