# Generated by Django 5.1.7 on 2025-04-16 08:56

import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_users_workspaces_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_workspaces',
            name='user_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('can_edit', 'Can Edit'), ('can_view', 'Can View')], default='can_view', max_length=8),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=workspaces.models.workspace_image_upload_path),
        ),
    ]
