# Generated by Django 5.1.7 on 2025-04-19 11:27

import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_users_workspaces_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('pending'), ('accepted'), ('rejected')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='users_workspaces',
            name='user_role',
            field=models.CharField(choices=[('owner'), ('can_edit'), ('can_view')], default='can_view', max_length=8),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=workspaces.models.workspace_image_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='users_workspaces',
            unique_together={('user', 'workspace')},
        ),
    ]
