# Generated by Django 5.1.7 on 2025-04-18 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_users_workspaces_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users_workspaces',
            unique_together={('user', 'workspace')},
        ),
    ]
