# Generated by Django 5.1.7 on 2025-04-19 12:05

import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_alter_invite_status_alter_users_workspaces_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='expire_date',
            field=models.DateField(default=workspaces.models.default_invite_expire_date, editable=False),
        ),
    ]
