# Generated by Django 5.1.7 on 2025-04-19 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_invite_expire_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver', 'workspace'), name='unique_pending_invite'),
        ),
    ]
