# Generated by Django 5.1.7 on 2025-04-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_users_workspaces_unique_together'),
        ('workspaces', '0006_invite_expire_date'),
    ]

    operations = [
    ]
