# Generated by Django 5.1.7 on 2025-04-19 14:46

from django.db import migrations , models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_alter_invite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Workspace',
            name='code',
            field=models.UUIDField(null=True, editable=False),
        ),
    ]
