# Generated by Django 5.1.7 on 2025-04-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_add_workspace_code_field'),
        ('workspaces', '0009_fix_workspace_code_migrations'),
    ]

    operations = [
    ]
