# Generated by Django 5.1.7 on 2025-04-20 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_merge_20250419_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace_Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(editable=False, max_length=255, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('valid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'workspace_invitations',
            },
        ),
        migrations.RemoveConstraint(
            model_name='invite',
            name='unique_pending_invite',
        ),
        migrations.AddField(
            model_name='workspace_invitation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='workspaces.workspace'),
        ),
    ]
