# Generated by Django 5.1.7 on 2025-04-20 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_workspace_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace_invitation',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
