# Generated by Django 5.1.7 on 2025-04-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_merge_20250420_1020'),
        ('workspaces', '0012_alter_workspace_code_and_more'),
    ]

    operations = [
    ]
