# Generated by Django 5.1.7 on 2025-04-12 16:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='Users\\default.png', upload_to=users.models.user_image_upload_path),
        ),
    ]
