# Generated by Django 5.1.7 on 2025-04-13 23:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='defaults/user/default.png', upload_to=users.models.user_image_upload_path),
        ),
    ]
