# Generated by Django 5.1.7 on 2025-04-14 11:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='defaults/user/default.png', upload_to=users.models.user_image_upload_path),
        ),
    ]
