# Generated by Django 5.1.7 on 2025-04-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
        ('users', '0004_client_alter_user_image'),
    ]

    operations = [
    ]
