# Generated by Django 5.1.7 on 2025-04-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250416_1152'),
        ('users', '0004_merge_20250418_1355'),
    ]

    operations = [
    ]
