# Generated by Django 5.1.7 on 2025-04-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250416_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
