# Generated by Django 5.1.7 on 2025-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250418_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
